### ISSUE TITLE
Retry support?

### ISSUE THREAD

**Issue by seancostigan** [saleem-mirza/serilog-sinks-azure-analytics#10]
Does this sink support retry logic, in the case where it can't connect to Log Analytics? I see in the base Serilog documentation where retry logic is referenced (https://github.com/serilog/serilog/wiki/Reliability#asynchronousbatched-network-operations) but it includes a note that the sink must derive from PeriodicBatchingSink to get this behavior. However, the Azure Analytics sync uses it's own ILogEventSink. Is the retry logic supported some other way?

**Comment by saleem-mirza** [comment]
@seancostigan at this time, this sink doesn't support retry logic. I intentionally dropped this feature for sake of simplicity, portability and also arguably performance. Retry needs a lot of moving parts which makes sink less portable e.g. how many times it needs to try and how often. Does it need to save log messages somewhere if sink is not able to reach destination.
If your application can't afford loosing log, I'd suggest to consider either FileSink or SQLite Sink.

**Comment by seancostigan** [comment]
@saleem-mirza I have taken a shot at writing a custom sink for Log Analytics, which inherits from PeriodicBatchingSink. I have patterned this after the other Sinks that use PeriodicBatching (AzureTableStorage, CouchDB, etc.)  The retry logic appears to be working as expected. I'm curious as to why you created your own batching logic rather than using the Periodic Batching. Would you be interested in accepting a PR with these changes?

**Comment by saleem-mirza** [comment]
@seancostigan, sorry for late reply. I was traveling. As I mentioned in my last reply, sink doesn't not support retry logic if something goes wrong with network for sake of simplicity.  Regarding your second question, I wrote my own logic way before PeriodicBatching came into picture. Both provides roughly same functionality.
