### ISSUE TITLE
AzureLogAnalyticsSink  should use UTF-8 encoding for signature

### ISSUE THREAD

**Issue by pbolduc** [saleem-mirza/serilog-sinks-azure-analytics#11]
According the docs, encoding should be UTF8 not [ASCII](https://github.com/saleem-mirza/serilog-sinks-azure-analytics/blob/d6e8bc11736c70f5a2a2ff71c8ac975848205b5a/src/Serilog.Sinks.AzureAnalytics/Sinks/AzureAnalytics/AzureLogAnalyticsSink.cs#L107) when computing the HMAC-SHA256 signature.

https://docs.microsoft.com/en-us/rest/api/loganalytics/create-request

**Comment by saleem-mirza** [comment]
@pbolduc, thanks for bringing it up with suggestion. it has been fixed.
