### ISSUE TITLE
Using ASP.Core 2.0 No Output

### ISSUE THREAD

**Issue by cgountanis** [saleem-mirza/serilog-sinks-azure-analytics#13]
```
Log.Logger = new LoggerConfiguration()
                //.MinimumLevel.Information()
                //.MinimumLevel.Override("Microsoft", LogEventLevel.Debug)
                //.MinimumLevel.Override("System", LogEventLevel.Debug)
                .Enrich.FromLogContext()
                .WriteTo.Console()
                .WriteTo.RollingFile("logs/log-{Date}.log")
                .WriteTo.AzureLogAnalytics(workspaceId: configuration["Serilog:WorkspaceId"], authenticationId: configuration["Serilog:AuthenticationId"], logName: "TESTLOGNAME")
                .CreateLogger();
```

I tripe checked the authenticationId and workspaceId and nothing is appearing in AzureLogAnalytics, I even tried with fake string id data and no error or logs. How do you even troubleshoot this?

**Comment by cgountanis** [comment]
```
"resultCode": "200",
      "success": true,
      "type": "Http",
      "target": "BLANKEDOUT.ods.opinsights.azure.com",
      "properties": {
        "AspNetCoreEnvironment": "Development",
        "DeveloperMode": "true"
      }
```

Seems like it is sending, does it have anythign to do with AspNetCoreEnvironment or DeveloperMode?

**Comment by saleem-mirza** [comment]
Sinks can take upto 10 seconds to transmit log to Azure if there aren’t enough messages usually around batch of 100 messages. However, Azure portal can take around 15 minutes to show messages there so please be patient ;)

It has nothing to do with environment or developer mode.

**Comment by cgountanis** [comment]
> It has nothing to do with environment or developer mode.

Great rules that out. Yes, I see the 200 OK message and the SysAdmin does see the LogNames and some random data, just be the delay that is causing us some testing issues.

Tough trying to figure out if a custom format/output is required. Does it just log everything available based on the MinimumLevel settings?

**Comment by saleem-mirza** [comment]
Yes.

**Comment by cgountanis** [comment]
Guess the issue just needs to be tweaked and tested on our end. Will be testing in the morning, Thank you for the information!

**Comment by saleem-mirza** [comment]
Please keep me posted.

**Comment by cgountanis** [comment]
We are 100% good. We even added middleware to capture the request/header information and it all seems to be coming in.

`app.UseMiddleware<RequestLogger>()`

```
public class RequestLogger
{
    readonly RequestDelegate _next;

    public RequestLogger(RequestDelegate next)
    {
        _next = next;
    }

    public async Task Invoke(HttpContext context)
    {
        using (LogContext.PushProperty("Headers", context.Request.Headers, destructureObjects: true))
        {
            await _next.Invoke(context);
        }
    }
}
```
