### ISSUE TITLE
"unicode" problem with accents

### ISSUE THREAD

**Issue by eduardoluizm** [saleem-mirza/serilog-sinks-azure-analytics#15]
Hi, 

I'm trying to send logs to azure, but when the log has accents like 'ç ã ó' it dosn't work. Log Analytics API returns a 403 error.

What should I do?

Same scenario on comments: https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-data-collector-api

**Comment by eduardoluizm** [comment]
@saleem-mirza could u help me?

**Comment by saleem-mirza** [comment]
@eduardoluizm, Indeed. I'll investigate this issue and let you know.

**Comment by saleem-mirza** [comment]
@maldworth, please check https://www.nuget.org/packages/Serilog.Sinks.AzureAnalytics/2.1.0-dev-00068
after wiggling around, it appears to be fixed now. I think issues is how Log Analytics API computes hash.
