### ISSUE TITLE
Log Message not show in the OMS.. only standard cols

### ISSUE THREAD

**Issue by BlueComFin** [saleem-mirza/serilog-sinks-azure-analytics#16]
Maybe i'm doing this wrong.. but i see only the logname, timestame, system cols in the OMS portal for the messages that i'm sending.. the actual log message text is not showing up.. do we need a custom formatter for this?
If so, can you share that?

**Comment by saleem-mirza** [comment]
It takes some time before showing up in portal. Please wait for 10 minutes and check again.
