### ISSUE TITLE
Q: What is the valid JSON configuration for *this* sink?

### ISSUE THREAD

**Issue by mmisztal1980** [saleem-mirza/serilog-sinks-azure-analytics#17]
I've attempted to configure the sink using the following piece of JSON:

```json
"Serilog": {
    "MinimumLevel": "Debug",
    "WriteTo": [
      {
        "Name": "AzureAnalytics",
        "Args": {
          "workspaceId": "<my-oms-workspace-id>",
          "authenticationId": "<my-oms-portal-key1>",
          "logName": "Application"
        }
      },
      {
        "Name": "Console"
      }
    ],

    "Enrich": [ "FromLogContext", "WithMachineName", "WithProcessId" ],

    "Properties": {
      "Application": "my-app",
      "Stage": "DEV"
    }
  }
```

Having started the app, no logs have appeared in OMS within 1hr after logging took place. After I've tried the fluent API to configure the sink, everything worked.

- Is JSON supported in order to configure the sink?
- If 'yes', what is the proper way of configuring the sink?
- If 'no' can this be supported?

Best regards,
/Maciej

**Comment by mmisztal1980** [comment]
Just found the issue, Serilog:WriteTo:0:Name should be **AzureLogAnalytics** . Leaving this for others struggling with the same issue.

**Comment by saleem-mirza** [comment]
👍
