### ISSUE TITLE
Consider changing array handling

### ISSUE THREAD

**Issue by mkosieradzki** [saleem-mirza/serilog-sinks-azure-analytics#19]
Currently arrays are flattened into multiple numbered columns.

Azure Log Analytics supports `mvexpand` which allows to generate multiple rows from single row entry with a dynamic array field. I think it could be beneficial to replace array flattening with mvexpand-compatible dynamic type.

**Comment by saleem-mirza** [comment]
@mkosieradzki good suggestion. Unfortunately, it's default API behavior which is written by Microsoft so I don't have much control over it unless, I write custom wrapper around API and it warrants quite bit time and effort.

**Comment by saleem-mirza** [comment]
@mkosieradzki please check https://www.nuget.org/packages/Serilog.Sinks.AzureAnalytics/2.1.1-dev-00097
I have removed array flattening to columns.

**Comment by mkosieradzki** [comment]
@saleem-mirza Thanks a lot for a super-quick fix attempt. I will give it a try on Monday (maybe I will manage to do this today).

I went through the API couple days ago and you are right there is no straightforward way documented for arrays. If this works it would be great, I have been using a workaround to use string for arrays and do parse_json in log analytics, but it's a suboptimal approach.

**Comment by mkosieradzki** [comment]
@saleem-mirza It seems that for some arrays messages are logged correctly as string (what makes it possible to use parse_json and mvexpand) - that's a HUGE improvement, but for some no properties are logged.

Usually the messages appearing earlier in Azure Log Analytics are getting broken and the latter are being logged correctly.

Messages logged correctly (destructured to properties) and incorrectly (no destructuring), have very similar source in Compact file log. So I don't believe it has anything to do with the message structure.

**Comment by saleem-mirza** [comment]
Unfortunately, there is no perfect solution for this problem. You may loose some information especially nested objects if I don't flatten it. This is give and take :)

Originally, idea was not to loose any information so flattening array elements into their own columns.

**Comment by mkosieradzki** [comment]
@saleem-mirza That's rater not it. The flatening works just great. There is some minor bug probably in batching or somewhere else. Because this message goes ok:
```
{"@t":"2018-01-13T18:56:37.9939712Z","@m":"\"admin\" made request for \"Yr+vub9CxECDckY7ArEMPw==\" using viewset null; { requestType: \"planQuery\", queries: [{ queryType: \"getPlanMetadata\", metadataKind: \"GetPlanMetadata\" }] }; Response: { status: \"success\" }","@i":"8752a379","User":"admin","Plan":"Yr+vub9CxECDckY7ArEMPw==","Viewset":null,"Request":{"requestType":"planQuery","queries":[{"queryType":"getPlanMetadata","metadataKind":"GetPlanMetadata"}]},"Response":{"status":"success"},"SourceContext":"P2ware.Pts.AuditLog"}
```

This one goes wrong:
```
{"@t":"2018-01-13T18:58:00.4645336Z","@m":"\"admin\" made request for \"Yr+vub9CxECDckY7ArEMPw==\" using viewset null; { requestType: \"planQuery\", queries: [{ queryType: \"getPlanMetadata\", metadataKind: \"GetPlanEditorMetadata\" }] }; Response: { status: \"success\" }","@i":"8752a379","User":"admin","Plan":"Yr+vub9CxECDckY7ArEMPw==","Viewset":null,"Request":{"requestType":"planQuery","queries":[{"queryType":"getPlanMetadata","metadataKind":"GetPlanEditorMetadata"}]},"Response":{"status":"success"},"SourceContext":"P2ware.Pts.AuditLog"}
```

I've made additional checks and even this one goes later ok:
```
{"@t":"2018-01-13T19:22:30.4574160Z","@m":"\"admin\" made request for \"Yr+vub9CxECDckY7ArEMPw==\" using viewset null; { requestType: \"planQuery\", queries: [{ queryType: \"getPlanMetadata\", metadataKind: \"GetPlanEditorMetadata\" }] }; Response: { status: \"success\" }","@i":"8752a379","User":"admin","Plan":"Yr+vub9CxECDckY7ArEMPw==","Viewset":null,"Request":{"requestType":"planQuery","queries":[{"queryType":"getPlanMetadata","metadataKind":"GetPlanEditorMetadata"}]},"Response":{"status":"success"},"SourceContext":"P2ware.Pts.AuditLog"}
```

and it differs only by timestamp...

It seems to be happening only to the very first messages after creating a new log...

**Comment by saleem-mirza** [comment]
@mkosieradzki, reverted back to original implementation. However, I couldn't replicate issues you mentioned. I'm able to see very first message but it takes painfully long time to appear on MOMS.

In my internal investigation on client side, message is transmitted to Azure almost instantly. Lets wait and see. We all are learning from each other, no one is perfect... including MSFT :)

**Comment by mkosieradzki** [comment]
@saleem-mirza :)

Yup, the initial 20 minutes+ delay is super painful for development/diagnostics.

My current guess is that the optimal representation for arrays today is to send them as JSON serialized to string - this is what Log Analytics seems to infer from the couple first messages.

If you send JSON array as string it even shows it nicely in the UI (it's a fully supported scenario called "nested json"). You only need to call parse_json before using mvexpand.

I believe that the issue with the first messages, I have mentioned earlier, is some kind of peculiarity of Azure Analytics column-type inference mechanism. I suppose that if you send it already as string (to avoid type inference) it will work just fine from the first shot.

BTW. Thanks a lot for your effort to make this Azure Analytics Sink really useful! I really appreciate it.

**Comment by saleem-mirza** [comment]
Well, this is what I was thinking too. But problem is that array can contain nested objects, so not sure if Log Analytics supports it.

**Comment by mkosieradzki** [comment]
If array is serialized as string it works perfectly (even very complex structures) - you can query json objects using 'dot' notation in Log Analytics, split them many times using mvexpand, etc. Works just great.

**Comment by mkosieradzki** [comment]
@saleem-mirza Works like gold (without any enriching modifications)! Thanks!

For example:
`PtsAuditLogD3_CL | project q = parse_json(LogProperties_Request_queries_s) | filter q != '' | mvexpand q | project q.queryType`

**Comment by saleem-mirza** [comment]
Glad it worked for you 👍
