### ISSUE TITLE
Add New JSON ContractResolver Optional Configuration Parameter

### ISSUE THREAD

**Issue by x3haloed** [saleem-mirza/serilog-sinks-azure-analytics#23]
I would like to suggest a change to the API to allow specification of the ContractResolver that AzureAnalytics's internal JSON conversion logic should use.

I have several projects that I'm using the AzureAnalytics sink with, including ASP.NET Core 2.0 apps and an ASP.NET Web Forms app. My Web Forms application is set to use a `CamelCasePropertyNamesContractResolver` by default, but the others are not. Example:
```
JsonConvert.DefaultSettings = () => new JsonSerializerSettings
{
    ContractResolver = new CamelCasePropertyNamesContractResolver()
};
```

This is creating a problem for me where I have several custom fields in Azure Log Analytics that differ by character casing, but should really be the same field. Example: logMessage_s vs LogMessage_s.

Looking through the AzureAnalytics source code, it appears that JSON converstion calls use the global/static Json.NET settings.

Instead of having to change global settings for all of my projects to use the same defaults, I'm hoping that a new optional configuration parameter could be added to specify which contract resolver to use when serializing and serializing JSON.

**Comment by saleem-mirza** [comment]
Please help me in understanding. Unless you have structures with same names but with different casing, I don't think there will be any issue unless you are collecting log by means other than this sink. In my humble opinion, if some applications are not logging correct data, than code responsible for this behavior needs to be fixed. Sink is a medium and not supposed to alter behavior and should transmit to destination whatever it is being fed.

**Comment by x3haloed** [comment]
> Sink is a medium and not supposed to alter behavior and should transmit to destination whatever it is being fed.

Exactly. The issue is that it _is_ altering behavior and transferring something different than what it is fed.

Consider the following two simple programs:

Program A:
```
using Serilog;

namespace SerilogSampleConsoleAppA
{
    class Program
    {
        static void Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
                .WriteTo.AzureAnalytics("my-workspace-id", "my-authentication-id")
                .Enrich.WithProperty("AppName", "Program A")
                .CreateLogger();

            Log.Information("Hello from Program A");
        }
    }
}
```

Program B:
```
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using Serilog;

namespace SerilogSampleConsoleAppB
{
    class Program
    {
        static void Main(string[] args)
        {
            JsonConvert.DefaultSettings = () => new JsonSerializerSettings
            {
                ContractResolver = new CamelCasePropertyNamesContractResolver()
            };

            Log.Logger = new LoggerConfiguration()
                .WriteTo.AzureAnalytics("my-workspace-id", "my-authentication-id")
                .Enrich.WithProperty("AppName", "Program B")
                .CreateLogger();

            Log.Information("Hello from Program B");
        }
    }
}
```

If you were to run each of those applications once, you would receive two log entries in Azure Log Analytics like the following:
`search *`

| TimeGenerated | LogProperties_Application_s | Message_s | logProperties_Application_s | message_s |
| ------------ | ------------- | ------------- | ------------- | ------------- |
| 2/28/2018 4:49:11.486 PM | Program A | Hello from Program A |  |  |
| 2/28/2018 4:50:12.283 PM |  |  | Program B | Hello from Program B |

As you can see the same input was passed to Serilog/AzureAnalytics sink, but not it's not possible to filter all logs against a single property name

**Comment by saleem-mirza** [comment]
@x3haloed thanks for putting example together. This definitely helped me in understanding of issue. However, as I said earlier, a communication library is suppose to not alter  data in flight. In your example, change is being induced by external configuration in your case by setting configuration on static instance of Json.

But I do see value in your suggestion to isolate such side effects and will give consumer option to fine tune this behavior in next release. 

Once again, thank you for stepping up with suggestion along with great example. 

👍 💯

**Comment by x3haloed** [comment]
You're welcome, and thank you for your time.

**Comment by saleem-mirza** [comment]
I have rolled out suggested feature recently. Please verify and let me know about your thoughts.

**Comment by x3haloed** [comment]
I installed the latest version, and it works well. Thank you!!
