### ISSUE TITLE
Azure analytics issue

### ISSUE THREAD

**Issue by ksrinu** [saleem-mirza/serilog-sinks-azure-analytics#24]
Hi ,

I add Serilog 2.6 and Serilog.Sinks.AzureAnalytics 2.2.5 versions on visual studio 2015.

I am trying to upload into Azure analystics. Its not uploading .

var logger = new LoggerConfiguration()
                       .WriteTo.AzureAnalytics(workspaceid,PrimaryKey,batchSize:1).CreateLogger();
            logger.Information("Serilog Test");

Please let me know how can i fix this.

Thanks,

**Comment by saleem-mirza** [comment]
Do you get any specific error?

**Comment by ksrinu** [comment]
I am not getting any error.

I used below code to check the logs.

 var file = File.CreateText("Serilog.txt");
Serilog.Debugging.SelfLog.Enable(TextWriter.Synchronized(file));

**Comment by saleem-mirza** [comment]
It takes some time to index log on azure. Check back in an hour in azure portal.

**Comment by ksrinu** [comment]
I have been testing from last 2 days. None of the logs created in azure portal.

**Comment by saleem-mirza** [comment]
I can confirm there is no issue with sink. Used following code:

```csharp
using (var logger = new LoggerConfiguration()
	.WriteTo.AzureAnalytics(
		"******************************",
		"******************************")
	.CreateLogger())
{
	logger.Information("This is test log from Serilog");
}

Console.ReadKey();
```
If you still can't find log in Azure portal (Log Search), make sure you have valid credentials.
