### ISSUE TITLE
Please make parameter "batchSize" non-optional.

### ISSUE THREAD

**Issue by tseshevsky** [saleem-mirza/serilog-sinks-azure-analytics#25]
Hi,
Please make parameter "batchSize" non-optional, because it makes for a better usability.
I just spent several hours trying to figure out why I can't see my logs in Azure Log Analytics. And I found out that the reason was in batchSize = 100 by default only when my colleague started load test with thousands of request.
Or at least add a warning to the readme, that if you can't see any logs, set batchSize to 1 for dev purposes.

**Comment by saleem-mirza** [comment]
Please see https://github.com/saleem-mirza/serilog-sinks-azure-analytics/blob/dev/README.md I clearly mentioned what are optionals and default values.
