### ISSUE TITLE
Console App - UnhandledError - Messages not making it to Azure but am using Log.CloseAndFlush()

### ISSUE THREAD

**Issue by shawndube** [saleem-mirza/serilog-sinks-azure-analytics#29]
I have a console app that is used as a webjob in Azure. I hooked up to the UnhandledException event like this:
System.AppDomain.CurrentDomain.UnhandledException += UnhandledExceptionTrapper;

private static void UnhandledExceptionTrapper(object sender, UnhandledExceptionEventArgs e)
{
   logger.LogError((Exception)e.ExceptionObject, "Unhandled Error");
   Log.CloseAndFlush();
}

Note I am using the Log.CloseAndFlush() call at the end.

My configuration has sinks for console, rollingfile, azureanalytics and seq. I am getting the Error logged to all the sinks except AzureAnalytics. Is there something else I need to do?

Thx!
Shawn

**Comment by saleem-mirza** [comment]
@shawndube please try https://www.nuget.org/packages/Serilog.Sinks.AzureAnalytics/2019.1.20-dev-00141 and see if it work.
