### ISSUE TITLE
Adding support for LevelSwitch for this sink?

### ISSUE THREAD

**Issue by maulik13** [saleem-mirza/serilog-sinks-azure-analytics#30]
We have a configuration setup where we can dynamically change the logging level of different sinks. However, this is not possible at the moment with Azure analytics sink. But available in file and console sinks.

**Comment by saleem-mirza** [comment]
I'm not sure if I understood your suggestion correctly. Please add an example how do you control log level dynamically?

**Comment by maulik13** [comment]
The following issue perhaps explains what I am after in Azure analytics sink. 

https://github.com/serilog/serilog/issues/505

By utilizing LoggingLevelSwitch at the sink level, we can dynamically change what event level is being reported to Azure analytics. 

I hope this is helpful.

**Comment by saleem-mirza** [comment]
@maulik13. please see https://www.nuget.org/packages/Serilog.Sinks.AzureAnalytics/3.5.0-dev-00124 with suggested feature. I'd appreciate your feedback.
