### ISSUE TITLE
Behind a Proxy?

### ISSUE THREAD

**Issue by Onjay** [saleem-mirza/serilog-sinks-azure-analytics#31]
I have some devices which are behind Proxies, and I'm not receiving data from them, although Azure Analytics is recording heartbeat and some performance counter data. Other devices which are not behind proxies are working perfectly, and I can see the logs. Is there a Proxy setting like there is for the MMA app?

DNS resolution of the service name <workspaceID>.oms.opinsights.azure.com failed.  Please check that the computer has Internet access or that a HTTP proxy has been configured for the system.  The query will be retried later.  The article KB3126513 has additional troubleshooting information for connectivity issues. 
 
URL for Operation: https://<workspaceID>.oms.opinsights.azure.com/ConfigurationService.Svc/GetCurrentConfigurationCookie 
Proxy Host:

**Comment by saleem-mirza** [comment]
Please see if this link help you. 

https://docs.microsoft.com/en-us/dotnet/framework/network-programming/proxy-configuration

**Comment by kudlatiger** [comment]
Any update on this?

**Comment by saleem-mirza** [comment]
@kudlatiger see https://docs.microsoft.com/en-us/dotnet/framework/network-programming/proxy-configuration

**Comment by eltjo** [comment]
@kudlatiger maybe this PR can be useful https://github.com/saleem-mirza/serilog-sinks-azure-analytics/pull/62
