### ISSUE TITLE
Newtonsoft.Json versions

### ISSUE THREAD

**Issue by Gerboa** [saleem-mirza/serilog-sinks-azure-analytics#34]
I have a project which is stuck on **Newtonsoft.Json v9.0.1** and now need to output to Log Analytics but the current sink requires **v11.0.2**.

How can I use this sink without updating everything to **v11.0.2** (other dependencies _prevent_ updating the project)?

**Comment by saleem-mirza** [comment]
Well, you can use older nuget package. 
https://www.nuget.org/packages/Serilog.Sinks.AzureAnalytics/1.7.45

**Comment by Gerboa** [comment]
That version doesn't successfully connect to Azure.
