### ISSUE TITLE
Problems in handling large amount of logs

### ISSUE THREAD

**Issue by htuomola** [saleem-mirza/serilog-sinks-azure-analytics#35]
**Background**
Hi, I've been using this library (thanks!) but have recently been seeing an unexpectedly high network traffic and CPU usage. After a while of diagnosing I found that the traffic graph was most certainly caused by failing HTTP calls to log analytics. In another logs we see those dependencies fail with 404 Not Found. I looked into the [Azure API specs](https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-data-collector-api#return-codes) for this and it seems that 404 means "_Either the URL provided is incorrect, or the request is too large [over 30MB, mentioned elsewhere in page]._". Because much of the calls were succeeding and the URL seems fixed, that most likely wasn't an issue (unless an error on their part).

**Problem**
This lead me to looking at the send & retry logic and I think it surfaces the problem(s):
- Currently the library tries to send the whole batch as one request, regardless of the request size (so this might exceed 30MB)
- If the call fails, for any reason, it waits for 10 seconds, put messages back to original list and then retries (with even more messages if there are new ones & batch wasn't "full" earlier)

Now, it the request was too large to begin with, the messages will just pile up and retrying every 10 seconds isn't gonna make it any better.

_Sidenote: I need to look at our log calls to see if we're logging anything unintentionally large that surfaced this issue but I suppose it does make sense fixing anyway._

With high enough message & batch size I was able to repro the failing calls locally - though in master branch but the code in dev seems similar.

**Proposed fix (PR)**
It seems pretty simple to split the log events to multiple batches inside of `AzureLogAnalyticsSink.WriteLogEventAsync(..)`. Just by keeping track of amount of bytes in content and limiting to under 30 MB removed all call failures for me. I have a local fork of this with the fix done so I if you're ok I can submit a PR (after some polishing).

**Related note of memory usage:**
While testing this, even with fixed version, the simple console app was using quite a large amount of memory. I did a bit of profiling with dotMemory and at least part of the reason seemed to be the [large amount of large] strings that are allocated for json inside of `WriteLogEventAsync()`. I've reimplemented it using a combination of MemoryStream and StreamWriter and the memory usage seems much more stable now. Would you be welcome for that PR too? How about the issue, can we keep both things in this same one or create a separate one for the memory one?

Edit: the memory findings are actually not that straight-forward. I've made it different but have to do some more testing to see if it's better or worse :smile:.

**Comment by saleem-mirza** [comment]
@htuomola, thank you very much for diagnostics. I will appreciate if you can send me a few dumps of process during high cpu and memory usage.

However, I believe this issue might not be because of accumulation of messages when sink is not able to send to Azure as you mentioned earlier. I'm adding messages back to queue and sending a them in configurable batch size (default 100).

Potentially, I smell issue in `Pump` method in BatchProvider.cs
If you see there, I'm using Semaphore allowing parallel requests of up to number of CPU cores. I believe this might be overloading network traffic to Azure to the point where it starts rejecting log.

However, I will welcome any improvements in memory consumption. Please feel free to raise PR.

Thank you.

**Comment by htuomola** [comment]
Granted I wasn't able to repro the exact behavior fully but with large batch size and message size it's possible to cause a situation in which the API request is over 30MB (actually limit seems to be a bit less, but refraining to < 30 000 000 bytes seems to fix it) and it fails. This test was using a batch of 1000 messages of 30KB each. The message size might be unrealistic but at least it should be specified in the docs that average log message size (serialized) should be less than `30 MiB / batchSize`.

With over 30MiB request the http call causes an exception as the connection is just closed by the other end. Based on their docs, if it were a rate limiting issue, Azure should be responding with 429 status code instead.

I wonder if the dump contents would also contain my log analytics credentials, which would be unfortunate :smile:.

Here's the version which both limits batches to max 30MiB and uses stream (I can separate the two later) - only these two methods need to be modified.

```csharp
protected override async Task<bool> WriteLogEventAsync(ICollection<LogEvent> logEventsBatch)
{
	if ((logEventsBatch == null) || (logEventsBatch.Count == 0))
		return true;

	int processedMessages = 0;

	do
	{
		IEnumerable<LogEvent> batch = logEventsBatch.Skip(processedMessages);
		var batchEventCount = 0;

		using (var ms = new MemoryStream())
		using (var streamWriter = new StreamWriter(ms, Encoding.UTF8))
		{
			streamWriter.Write("[");
			
			foreach (var logEvent in batch)
			{
				IDictionary<string, object> keys = logEvent.Dictionary(_storeTimestampInUtc, _formatProvider);
				JObject jObject = JObject.FromObject(keys, _jsonSerializer);
				var jsonString = JsonConvert.SerializeObject(jObject.Flaten(), _jsonSerializerSettings);

				// Limit batches to under 30MB, as required by Azure API
				// effective limit seems to be a bit lower than 30*1024^2
				if (ms.Length + jsonString.Length >= 30_000_000)
					break;

				if(batchEventCount > 0)
					streamWriter.Write(",");
				streamWriter.Write(jsonString);
				
				batchEventCount++;
			}

			streamWriter.Write("]");
			
			streamWriter.Flush();
			ms.Seek(0, SeekOrigin.Begin);

			var dateString = DateTime.UtcNow.ToString("r");
			var hashedString = BuildSignature((int)ms.Length, dateString, _authenticationId);
			var signature = $"SharedKey {_workSpaceId}:{hashedString}";

			SelfLog.WriteLine("Sending batch of {0} events, total of {1} bytes", batchEventCount, ms.Length);
			var result = await PostDataAsync(signature, dateString, ms).ConfigureAwait(false);
			if (result == "OK")
				processedMessages += batchEventCount;
		}
	} while (processedMessages < logEventsBatch.Count);

	return true;
}

private async Task<string> PostDataAsync(string signature, string dateString, MemoryStream stream)
{
	try {
		await _semaphore.WaitAsync().ConfigureAwait(false);

		Client.DefaultRequestHeaders.Clear();
		Client.DefaultRequestHeaders.Add("Authorization", signature);
		Client.DefaultRequestHeaders.Add("x-ms-date", dateString);

		var streamContent = new StreamContent(stream);
		streamContent.Headers.ContentType = MediaTypeHeaderValue.Parse("application/json");
		streamContent.Headers.Add("Log-Type", _logName);

		var response = await Client.PostAsync(_analyticsUrl, streamContent).ConfigureAwait(false);
		var message = await response.Content.ReadAsStringAsync().ConfigureAwait(false);

		SelfLog.WriteLine("{0}: {1}", response.ReasonPhrase, message);

		return response.ReasonPhrase;
	}
	catch (Exception ex) {
		SelfLog.WriteLine("ERROR: " + (ex.InnerException ?? ex).Message);

		return "FAILED";
	}
	finally {
		_semaphore.Release();
	}
}
```

**Comment by saleem-mirza** [comment]
@htuomola I have made a radical change and now message with size greater than 32MB will be dropped. However, if batch size exceeds 32MB limit, it will get split in smaller mini batches and relayed to Azure.

I hope new change should handle high CPU usage and Azure rejection (in case if jumbo message). I'll appreciate if you can run a test.
Please see https://www.nuget.org/packages/Serilog.Sinks.AzureAnalytics/3.5.0-dev-00127

**Comment by htuomola** [comment]
Thanks! I'll test with that to see if it resolves it. By the way, why 32 MB? 32 is the size of single field in docs (KB). The maximum size of API request is documented to be 30MB but in my testing limiting to 30*1024*1024 bytes was not enough. Limiting to 30 000 000 bytes did fix it though. Might be safer to use a bit lower threshold?

**Comment by saleem-mirza** [comment]
I'm just enforcing request size limit. 3000000 bytes to limit payload and rest is buffer for request overhead. 
It's safer to avoid absolute ceiling of 32MB request size.

**Comment by htuomola** [comment]
Right, but where is that 30000000 byte limit? I can only see the 32000000 bytes limit in here (used for both individual message and batch limit)?
https://github.com/saleem-mirza/serilog-sinks-azure-analytics/blob/f94f4450e5cfcc73805ec44f09883551d44dd23d/src/Serilog.Sinks.AzureAnalytics/Sinks/AzureAnalytics/AzureLogAnalyticsSink.cs#L168

https://github.com/saleem-mirza/serilog-sinks-azure-analytics/blob/f94f4450e5cfcc73805ec44f09883551d44dd23d/src/Serilog.Sinks.AzureAnalytics/Sinks/AzureAnalytics/AzureLogAnalyticsSink.cs#L48

**Comment by saleem-mirza** [comment]
Oh my bad. getting old so forgot what I coded :) please feel free for fix.

**Comment by htuomola** [comment]
No problem :smile:, PR created

**Comment by saleem-mirza** [comment]
Thank you @htuomola for investigation and suggesting solution.  Here is new nuget after your fix. Please let me know if it's good enough for this issue?

**Comment by htuomola** [comment]
I've been looking at the behavior for a bit less than a day now but I think the fixes in this issue alone definitely fix all the problems for me. Network and CPU usage have disappeared ~completely and memory usage is much lower and steadier too. 👍 

By the way, I think the counter decrement in here is incorrect? Just by not incrementing it and continuing would be correct? Oh and the log message still says 3**2** MB (my bad).
https://github.com/saleem-mirza/serilog-sinks-azure-analytics/blob/d813366ec9e94d8eec7d7c98c4bf634f02141cbf/src/Serilog.Sinks.AzureAnalytics/Sinks/AzureAnalytics/AzureLogAnalyticsSink.cs#L161-L162

**Comment by saleem-mirza** [comment]
Well, intention is to increment counter each time I add message to batch and if batch size exceeds allowable limit, decrement counter so will represent correct number of messages in mini batch. 

but I see your point. if very first message itself exceeds limit, counter can go negative. I'll fix this edge case.

good catch.
