### ISSUE TITLE
How can I configure the column  names ?

### ISSUE THREAD

**Issue by foote-Greg** [saleem-mirza/serilog-sinks-azure-analytics#40]
They are all so long that none of them will display in the various dropdowns to select from when creating queries and charts etc in azure log analytics

![image](https://user-images.githubusercontent.com/4241394/50045423-0dca6200-0058-11e9-8a02-f656a719ce65.png)

Here is an example of the drop downs

![image](https://user-images.githubusercontent.com/4241394/50045432-32bed500-0058-11e9-8f9e-eaa9f1fbe56c.png)

Is there a way to configure how the names are generated ?

**Comment by saleem-mirza** [comment]
@foote-Greg, unfortunately there is no simple solution.  These names corresponds to hierarchal properties names glued together and separated by "_" to make unique names.


If a property is nested deep down in hierarchy, it will have a longer name.

**Comment by thomaslevesque** [comment]
Hi @saleem-mirza, maybe for well-known properties the prefix could be made shorter? e.g. "prop_" or even "_" instead of "LogProperties_" ? And "ex_" instead of "LogException_" ?

**Comment by thomaslevesque** [comment]
(Sorry, the formatting was messed up in my previous comment. I fixed it)

Also, can we get rid of the type suffixes ? (`_s`, `_d`...)

**Comment by saleem-mirza** [comment]
Unfortunately we can't `_s` and `_d` are being appended by Microsoft and I have no control over there :)
However, you can simply logging structure by setting `flattenObject` to false. It will create nested properties and will not emit long names.
Please see documentation at https://github.com/saleem-mirza/serilog-sinks-azure-analytics

**Comment by thomaslevesque** [comment]
But `flattenObject` is only available in the current pre-release version, right? Do you expect to release a stable version soon?
