### ISSUE TITLE
Help with json structures

### ISSUE THREAD

**Issue by sicollins** [saleem-mirza/serilog-sinks-azure-analytics#43]
I think I may be misunderstanding how to log my objects as json into the log messages that are going in to Azure.

Say we had the following C# models:
```
public class Parent
{
	public Guid Id { get; set; } 
	public string Name { get; set; }
	public DateTime DateOfBirth { get; set; }
	public Child Child { get; set; }
}

public class Child
{
	public Guid Id { get; set; }
	public string Name { get; set; }
	public DateTime DateOfBirth { get; set; }
	public Grandchild Grandchild { get; set; }
}

public class Grandchild
{
	public Guid Id { get; set; }
	public string Name { get; set; }
	public DateTime DateOfBirth { get; set; }
}
```
And we set up the parent like this:
```
var family = new Parent
{
	Id = Guid.NewGuid(),
	Name = "The Parent",
	DateOfBirth = DateTime.Now.AddYears(-50),
	Child = new Child
	{
		Id = Guid.NewGuid(),
		Name = "The Child",
		DateOfBirth = DateTime.Now.AddYears(-30),
		Grandchild = new Grandchild
		{
			Id = Guid.NewGuid(),
			Name = "The Granchild",
			DateOfBirth = DateTime.Now.AddYears(-5),
		}
	}
};
```
This is what I want my LogMessage_s to contain:

```
FamilyLog: {"Id":"fb36502a-d258-4d27-80d0-27e490f56b36","Name":"The Parent","DateOfBirth":"1969-01-18T18:47:08.0846554+00:00","Child":{"Id":"0c6d0c8d-efa8-40de-978f-67d011a0088a","Name":"The Child","DateOfBirth":"1989-01-18T18:47:08.0850895+00:00","Grandchild":{"Id":"99430775-fba8-4082-85ae-c1271eb3dd69","Name":"The Granchild","DateOfBirth":"2014-01-18T18:47:08.0854919+00:00"}}}
```

So I can copy it out and it's valid json which I can then fire at an API using Postman without having to make any changes:
```
{
	"Id": "fb36502a-d258-4d27-80d0-27e490f56b36",
	"Name": "The Parent",
	"DateOfBirth": "1969-01-18T18:47:08.0846554+00:00",
	"Child": {
		"Id": "0c6d0c8d-efa8-40de-978f-67d011a0088a",
		"Name": "The Child",
		"DateOfBirth": "1989-01-18T18:47:08.0850895+00:00",
		"Grandchild": {
			"Id": "99430775-fba8-4082-85ae-c1271eb3dd69",
			"Name": "The Granchild",
			"DateOfBirth": "2014-01-18T18:47:08.0854919+00:00"
		}
	}
}
```

I have tried the following:

1. logger.LogDebug("FamilyLog: {@Family}", family); 
* this makes it appear with C# type names and properties not in quotes so not valid json

2. logger.LogDebug("FamilyLog: {Family}", family); 
* this make it appear as the parent type name only

3. logger.LogDebug("FamilyLog: {Family}", JsonConvert.SerializeObject(family));
* this adds the entire object as a json string but escaped \"

The info on this repo and on main serilog repo around structured objects isn't clear to me.

When the log appears in Azure , LogAnalytics seems to make a custom field out of every single object property in the tree, which in some cases I can see is desirable so you can query aganist them, but some of the models I'm  dumping into the log have hundreds of fields and deep nested structures, but don't appear as valid json which I can then extract and fire at my API.

I'm wondering if this is partly what's causing some of my logs to simply not appear in LogAnalytics, even though the sink appears to POST all batches and states OK for each: (see related ticket: https://github.com/saleem-mirza/serilog-sinks-azure-analytics/issues/42

Any help with this much appreciated.

**Comment by saleem-mirza** [comment]
how will you embed json in string without encoding?

`LogMessage_s` is a string property
