### ISSUE TITLE
Not able to view the Log in Azure Log Analytics

### ISSUE THREAD

**Issue by bibhusundarparida** [saleem-mirza/serilog-sinks-azure-analytics#44]
Hi,
I have created a Console application and  installed "Serilog.Sinks.AzureAnalytics(4.0.0)".Eventghough the code is not throigh any exception or errorr i am not able to view the logs in the AzureLogAnalytics workspace uisng using azure portal.
However, if i use DataCollectorAPI of Azure, directly , i am able to  view the logs. I am sure the Serilog Sink is alos using the same DataCollectorAPI internally. Please find below the set of code being used.

 var logger1 = new LoggerConfiguration()
          .WriteTo.AzureAnalytics(**WorkSpaceID**, **AuthenticationID**,"SerlogCustom")
          .CreateLogger();

                logger1.Information("New Error");

**Comment by saleem-mirza** [comment]
try disposing logger. `logger1.Dispose()` or wrap it around `using`

your application is terminating even before logger gets chance to send log to azure.
