### ISSUE TITLE
Not able to view the logged data in Azure Log Analytics

### ISSUE THREAD

**Issue by SASWATMALLIK** [saleem-mirza/serilog-sinks-azure-analytics#45]
Hi,
I have created a Console application and installed "Serilog.Sinks.AzureAnalytics(4.0.0)". When I am logging some custom data( **logEntity** ), It's logging but the custom data ( **logEntity** ) is not reflecting in the AzureLogAnalytics workspace of Azure portal. Please find below the set of code being used and the screenshot of data reflecting in the portal.

```
var logger = new LoggerConfiguration()
.WriteTo.AzureAnalytics(WorkSpaceID, AuthenticationID,"SerlogCustom")
.CreateLogger();

LogEntity logEntity = new LogEntity
                {
                    Category = GetCategory(),
                    LogTypes = LogType.Warning.ToString(),
                    Description = "description warning",
                    LogDateDateTime = DateTime.UtcNow,
                    ID = Guid.NewGuid()
                };
logger.Write(LogEventLevel.Error, "Microservice1",logEntity);
logger.Dispose();
```

![Azure2](https://user-images.githubusercontent.com/48519880/54285014-184cb700-45c7-11e9-8691-96251739b901.png)

**Comment by saleem-mirza** [comment]
It takes some time to show up in azure. So check back in an hour.

**Comment by SASWATMALLIK** [comment]
Hi Saleem,
Thanks for the reply, As suggested by you I had a look into the log which I had put yesterday, but the Custom Object(**LogEntity**)  is still not visible.

If you see the below code... When I am writing a Log using "**Write**" method the third parameter is the Custom Object (**LogEntity**) which I want to log.
 However, when I visit the **Azure Log analytics workspace-> Logs->CustomLogs** section, I can view the log entered without the Custom Object which I had passed in the third parameter of the "**Write**" method 


### **Code Snippet...**
var logger = new LoggerConfiguration()
.WriteTo.AzureAnalytics(WorkSpaceID, AuthenticationID,"SerlogCustom")
.CreateLogger();

**LogEntity logEntity** = new LogEntity
                {
                    Category = GetCategory(),
                    LogTypes = LogType.Warning.ToString(),
                    Description = "description warning",
                    LogDateDateTime = DateTime.UtcNow,
                    ID = Guid.NewGuid()
                };
logger.Write(LogEventLevel.Error, "Microservice1",**logEntity**);
logger.Dispose();


### **Screen Shot of the Log Analytics workspace**

![Azure2](https://user-images.githubusercontent.com/48519880/54332208-31934900-4643-11e9-83f6-3467f933f0dc.png)

**Comment by saleem-mirza** [comment]
sounds interesting. Its being used in production but anyway, try pre-release version https://www.nuget.org/packages/Serilog.Sinks.AzureAnalytics/19.3.10-dev-00142 and let me know if it works for you

**Comment by SASWATMALLIK** [comment]
Hi Saleem,
Thanks for the reply. I tried the pre-release version 
https://www.nuget.org/packages/Serilog.Sinks.AzureAnalytics/19.3.10-dev-00142 with the same code but still facing the same problem.

**Comment by saleem-mirza** [comment]
well, I'm not sure what's going on. I have tested with sample code and it works flawless. If it still doesn't work, check your code or configuration 

```csharp
	SelfLog.Enable(Console.Out);

	using (var logger = new LoggerConfiguration()
		.WriteTo.AzureAnalytics(
			    "**********",
			    "**********",
			    new ConfigurationSettings() 
			    {
				    Flatten = false
			    })
				.CreateLogger()) 
	{
		var logEntity = new
		{
			Category        = "Some Category",
			LogTypes        = "Warning",
			Description     = "description warning",
			LogDateDateTime = DateTime.UtcNow,
			ID              = Guid.NewGuid()
		};

		logger.Information("Logged {@logEntity}", logEntity);
	}
	
```

**Comment by SASWATMALLIK** [comment]
Hi Saleem,
Thanks, Now I am getting the message template formatted with the object in **LogMessage_s** field.
But my requirement is to get the individual properties of the object in separate columns in AzureLogAnalytics workspace.

**Example:**

     var logEntity = new
		{
			Category        = "Some Category",
			LogTypes        = "Warning",
			Description     = "description warning",
			LogDateDateTime = DateTime.UtcNow,
			ID              = Guid.NewGuid()
		};

But I want **_Category_**, **_LogTypes_**, **_Description_**, **_LogDateDateTime_** and  **_ID_** as separate columns with the existing columns(i.e-  **_SourceSystem_**,_**ManagementGroupName**_,...)  in the AzureLogAnalytics workspace so that I can query on these properties for dashboarding.
**Now how to achieve this?**

**Comment by saleem-mirza** [comment]
try `Flatten = true` and see how it goes

**Comment by SASWATMALLIK** [comment]
**Thanks**, Saleem. It's Working (**I got  what I was expecting**.)
