### ISSUE TITLE
Request support for Azure China for AzureOfferingType

### ISSUE THREAD

**Issue by will-beta** [saleem-mirza/serilog-sinks-azure-analytics#48]
Right now the AzureOfferingType only provide support for `azure.com` and `azure.us`.
I'd appreciate it can support for `azure.cn`.

**Comment by saleem-mirza** [comment]
@will-beta, thanks for bringing up issue with sink. I'll include support for our Chinese users and will publish it soon.

**Comment by will-beta** [comment]
@saleem-mirza Thanks a lot for the reply! Can I ask is there an ETA?

**Comment by saleem-mirza** [comment]
I'm still struggling to find reliable azure collector API offering for `.azure.cn`. This sink used Data Collector API for transferring logs. https://docs.azure.cn/zh-cn/azure-monitor/platform/data-collector-api
As you can see in documentation, there is no `.azure.cn' endpoint unless I'm missing something.

**Comment by will-beta** [comment]
@saleem-mirza Thanks for your kind reply!
Just found '.azure.cn' has been updated into this document. https://docs.azure.cn/zh-cn/azure-monitor/platform/data-collector-api

**Comment by saleem-mirza** [comment]
@will-beta, thanks for keeping tab on it and quick update.
I have update repo and published a beta version of nuget package. Please validate if it works. (unfortunately, I don't have azure china account).

https://www.nuget.org/packages/Serilog.Sinks.AzureAnalytics/4.6.0-dev-00154

**Comment by will-beta** [comment]
@saleem-mirza It works, except for a compatibility problem with `Microsoft.NET.Sdk.Functions`.
Could you modify the lowest version of `Newtonsoft.json` from `12.0.1` to `11.0.2`?

**Comment by saleem-mirza** [comment]
@will-beta what exactly issue is with SDK? I'm not sure going down is an option as this sink is being used by many other applications and developers.

**Comment by will-beta** [comment]
@saleem-mirza `Microsoft.NET.Sdk.Functions` is using the fixed version `11.0.2`. Thus it prevent installing your package into the project.

**Comment by saleem-mirza** [comment]
Thanks for quick reply. I have another version published with lower bound of Newtonsoft to 10.0.3. Please validate

**Comment by will-beta** [comment]
@saleem-mirza It works! Thank you so much!

**Comment by will-beta** [comment]
@saleem-mirza Another question: would you consider adding support for proxy?
Azure Log Analytics is only available in the East2 region in China, but our apps are deployed in another region and unable to move currently.
Proxy & VNet Peering could save us a lot of money for traffic fees across different azure regions.

**Comment by saleem-mirza** [comment]
Proxy and peering are more of configuration changes. It has nothing to do with sink itself. This sink is just a library agnostic of networking.

**Comment by will-beta** [comment]
Yes, they are configuration changes. 
It's just Azure App Service is a PaaS product, which doesn't support proxy configuration. There's no other way left for us.
We'd very appreciate that if this sink could support proxying.

**Comment by will-beta** [comment]
@saleem-mirza Could you publish a stable version? 
As for the functionality of proxying, I would like to cancel my request, because of high pricing of the Log Analytics.
Thanks so much for your help!

**Comment by saleem-mirza** [comment]
Done!
