### ISSUE TITLE
azureOfferingType not recognized

### ISSUE THREAD

**Issue by evochriso** [saleem-mirza/serilog-sinks-azure-analytics#56]
**Describe the bug**
I am using Serilog.Settings.AppSettings to configure the sink. When I try to supply the azureOfferingType parameter, it is ignored and the default Azure cloud (Public) is always used

**To Reproduce**
Install Serilog.Settings.AppSettings and craft an app.config file
Add these keys:

`
<add key="serilog:using:AzureLogAnalytics" value="Serilog.Sinks.AzureAnalytics" />
<add key="serilog:write-to:AzureLogAnalytics.logName" value="MyLogName" />
<add key="serilog:write-to:AzureLogAnalytics.workspaceId" value="XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" />
<add key="serilog:write-to:AzureLogAnalytics.authenticationId" value="[UBER BASE64 SECRET KEY]" />
<add key="serilog.write-to:AzureLogAnalytics.azureOfferingType" value="US_Government"/>
`

Start the app and see the sink is using the default offering of Public (azure.com) by observing the serilog self log messages:

ALERT: Serilog internal debug message: 2021-04-29T05:23:19.0658829Z ERROR: The remote name could not be resolved: 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX.ods.opinsights.**azure.com**'
ALERT: Serilog internal debug message: 2021-04-29T05:23:19.0668795Z Retrying after 5 seconds...

**Expected behavior**
The azureOfferingType parameter should be observed and the sink should be configured accordingly. The error above should have attempted to resolve the URL ...azure.**us**

**Screenshots**

**Additional context**
Is this the correct way to specify the azureOfferingType Enum when using AppSettings? i.e. 'Public', 'US_Government', etc

**Comment by saleem-mirza** [comment]
@evochriso does it work when using without AppSetttings?

**Comment by evochriso** [comment]
@saleem-mirza yes, if I use 
WriteTo.AzureAnalytics(workspaceId: "", authenticationId: "", logName: "", azureOfferingType: AzureOfferingType.US_Government)
the URL is correctly configured to .azure.us. 
It seems AppSettings is calling the wrong constructor, or at least not including the offering argument.

Thanks!

**Comment by evochriso** [comment]
Apologies for my mistake, this works fine when you set the key correctly. Doh.

```
<add key="serilog:write-to:AzureLogAnalytics.azureOfferingType" value="US_Government"/>
```
instead of:
```
<add key="serilog.write-to:AzureLogAnalytics.azureOfferingType" value="US_Government"/>
```
