### ISSUE TITLE
After Upgrade to 1.8.1 doen't work anymore

### ISSUE THREAD

**Issue by Giorgio-Montagnoli** [saleem-mirza/serilog-sinks-azure-analytics#7]
Hi,

if I upgrade from 1.7.45 to 1.8.1, serilog stops to register logs in Azure Log Analytics.
This is an example of how I track an exception.

      var logger = LogProvider.GetCurrentClassLogger();
      logger.FatalException("GLOBAL ERROR", exception);

Nothing more or less than a standard call to Serilog.
We use .NET 4.5. These are the packages we use

	<package id="Serilog" version="2.4.0" targetFramework="net45" />
	<package id="Serilog.Enrichers.AzureWebApps" version="1.0.2" targetFramework="net45" />
	<package id="Serilog.Enrichers.Environment" version="2.1.2" targetFramework="net45" />
	<package id="Serilog.Enrichers.ExceptionStackTraceHash" version="1.1.0" targetFramework="net45" />
	<package id="Serilog.Enrichers.HttpContextData" version="0.1.2" targetFramework="net45" />
	<package id="Serilog.Enrichers.Process" version="2.0.1" targetFramework="net45" />
	<package id="Serilog.Enrichers.Thread" version="3.0.0" targetFramework="net45" />
	<package id="Serilog.Formatting.Compact" version="1.0.0" targetFramework="net45" />
	<package id="Serilog.Sinks.AzureAnalytics" version="1.8.1" targetFramework="net45" />
	<package id="Serilog.Sinks.File" version="3.2.0" targetFramework="net45" />
	<package id="Serilog.Sinks.PeriodicBatching" version="2.1.0" targetFramework="net45" />
	<package id="Serilog.Sinks.RollingFile" version="3.3.0" targetFramework="net45" />
	<package id="Serilog.Sinks.Seq" version="3.2.0" targetFramework="net45" />
	<package id="SerilogMetrics" version="2.0.3" targetFramework="net45" />

Can you please help me?
Thanks

**Comment by saleem-mirza** [comment]
My apologies for inconvenience. I'll look at it tonight.

**Comment by saleem-mirza** [comment]
@Giorgio-Montagnoli please validate latest version from [nuget](https://www.nuget.org/packages/Serilog.Sinks.AzureAnalytics/1.8.2). I need to be more vigilant of what Microsoft is doing with it's API. They are keep changing.

**Comment by Giorgio-Montagnoli** [comment]
Hi, now we got this issue

> There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "Serilog.Sinks.AzureAnalytics, Version=1.8.2.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10, processorArchitecture=x86", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.

We are on a x64 architecture

**Comment by saleem-mirza** [comment]
This code is using AnyCPU as processor Architecture so try with AnyCPU and let me know.

**Comment by Giorgio-Montagnoli** [comment]
Hi, I am already building using AnyCPU
![croppercapture 1](https://cloud.githubusercontent.com/assets/21526219/24954151/6fa8e6ac-1f7e-11e7-85b4-561ea597b807.jpg)

**Comment by saleem-mirza** [comment]
I can confirm that it work with AnyCPU architecture but not with x64 with explicitly selected. I'll look into it.

**Comment by Giorgio-Montagnoli** [comment]
I think the problem could be in this line
    <PropertyGroup Condition="'$(TargetFramework)'!='netstandard1.6'">
        <DefineConstants>DEBUG;TRACE;NET45</DefineConstants>
        <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
    </PropertyGroup>
because I use VS 2015

**Comment by saleem-mirza** [comment]
Yes, you are spot on. I'm on VS2017 but will test in cross env.

**Comment by saleem-mirza** [comment]
Please try 1.8.3 and let me know if it works.

**Comment by Giorgio-Montagnoli** [comment]
Ok, now works perfectly.

Thank you
