### ISSUE TITLE
Batching?

### ISSUE THREAD

**Issue by warrenbuckley** [saleem-mirza/serilog-sinks-azure-analytics#9]
>Sink buffers log internally and flush to Azure Log Analytics in batches using dedicated thread for better performance.

Hi @saleem-mirza I have started to use your Serilog Sink to push data into our OMS account and based on the message above taken from your readme. It seems log items are not pushed immediately into OMS as I would have expected.

How often are items pushed/sent to OMS and can this be configured at all?

Currently I am using this snippet:

```
//SeriLog - Logging Configuration
//OMS Specific Sink Settings comes from AppSettings
Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Debug()
    .Enrich.WithProperty("ServiceVersion", Assembly.GetExecutingAssembly().GetName().Version.ToString()) //For every submission to OMS Logs (We log what version of this Service is being used)
    .ReadFrom.AppSettings()
    .CreateLogger();

//Debug mode for SeriLog internal logs not in any Sinks
//(Write to VS Debug Window)
Serilog.Debugging.SelfLog.Enable(msg => Debug.WriteLine(msg));

//Lets try to log something for testing
//Specifying the class that log is coming from
var myLogger = Log.ForContext<Service>();
myLogger.Information("Hello World");

var count = 123;
myLogger.Information("Warren Testing Count {Count} records", count);

//I expect each of these lines to be in OMS Azure log near enough instantly
var sensorInput = new { Latitude = 25, Longitude = 134 };
myLogger.Information("Processing {@SensorInput}", sensorInput);

for (int i = 0; i < 100; i++)
{
    myLogger.Information("Logging in a loop item {Counter}", i);
}
```

Do I need to use a `using` statement or explicitly call `Log.CloseAndFlush();` everytime I want to persist something immediately to OMS?

The data only seems to be persisted into OMS when my Console App has stopped running/being debugged.

**Comment by saleem-mirza** [comment]
@warrenbuckley logs are persisted to sink on three conditions (whichever occurs first)

1. Every 10 seconds
2. When events are accumulated up-to batch size (default 100)
3. Sink is closed (Log.CloseAndFlush)

When you use it in console application and console application exit right after logging (in case of your example), it's recommended to call Log.CloseAndFlush to ensure messages are sent to their destination.

**Comment by DinoSourcesRex** [comment]
@saleem-mirza Does the sink use batching or not? I think the readme is a little deceiving as a `batchSize` parameter is listed however both at the top and bottom of the readme it says that batching is not supported.

**Comment by saleem-mirza** [comment]
@DinoSourcesRex, yes this sink supports batching. Can you please point me out where readme says it's not supported?

**Comment by DinoSourcesRex** [comment]
@saleem-mirza Sure.

Line 2 in the [Readme](https://github.com/saleem-mirza/serilog-sinks-azure-analytics/edit/dev/README.md).

> ...Sink do support automatic batching of log messages ...

Line 66 in the [Readme](https://github.com/saleem-mirza/serilog-sinks-azure-analytics/edit/dev/README.md).

> Sink buffers log internally and flush to Azure Log Analytics in batches using dedicated thread for better performance.

---

The issue, to me, is more that it is unclear if batching is supported or not just reading the Readme, so thank you for clearing that up!

**Comment by saleem-mirza** [comment]
@DinoSourcesRex, you mentioned it doesn't support so was wondering if it's mistake. However we need to trust trust readme :)
