### ISSUE TITLE
Call to the Azure dataCollectionRules endpoint is returning 401 (TokenExpired)

### ISSUE THREAD

**Issue by faffb** [saleem-mirza/serilog-sinks-azure-analytics#94]
Hi, 

Thanks for providing this library.  Using the latest version (6.5.0).

**Describe the bug**
After a while, we don't receive the log entries anymore in LogAnalytics. It seems like that once the bearer token is expired, a call is done to get a new one, but the new token is not assigned to the Authorization header of the dataCollectionRules endpoint call. The call still uses the expired token.

**To Reproduce**
A while after the initialization (after 1 hour, the time the original bearer token is valid), no more log entries are received in LogAnalytics.

**Expected behavior**
The new token should be assigned to the Authorization header of the subsequent dataCollectionRules endpoint calls.

**Comment by saleem-mirza** [comment]
@faffb thank you for not only finding issue but also conducting detailed analysis. I have updated sink and would appreciate if you can please run a test and let me know if it works.

**Comment by faffb** [comment]
Hi @saleem-mirza,

Thanks for the reply and the update.

With the new version, a call to get a new token is done before the previous bearer token is expired, which is a good thing. But this new token is still not assigned to the Authorization header of the dataCollectionRules endpoint call. It seems like the bearer token is assigned to the Authorization header only in the constructor.

So once the original bearer token is expired, the call to the Azure dataCollectionRules endpoint is still returning 401 (TokenExpired).

**Comment by saleem-mirza** [comment]
ahh, thank you for your patience and support. I have reshuffle code and hopefully it should fix token issue. Unfortunately, I don't have access to Azure anymore :( so couldn't test.

**Comment by faffb** [comment]
No worries... There is still an issue; See the comment I have added in the latest commit for the explanation

**Comment by faffb** [comment]
The version 6.6.7 seems to fix the issue. I will do more tests on Monday but so far so good!
